---

- name: Prep
  ansible.builtin.include_tasks: prep.yaml

- name: Deploy (with k8s kubeconfig)
  block:

  - name: Deploy
    ansible.builtin.include_tasks: deploy.yaml
    when: jo_state|string == 'present'
  - name: Undeploy
    ansible.builtin.include_tasks: undeploy.yaml
    when: jo_state|string == 'absent'

  module_defaults:
    group/k8s:
      kubeconfig: "{{ jo_kubeconfig }}"
  when: jo_kubeconfig|string|length != 0

- name: Deploy (with k8s host and API key)
  block:

  - name: Deploy
    ansible.builtin.include_tasks: deploy.yaml
    when: jo_state|string == 'present'
  - name: Undeploy
    ansible.builtin.include_tasks: undeploy.yaml
    when: jo_state|string == 'absent'

  when: jo_kubeconfig == 'SetMe'
